# Generated by Django 3.0.6 on 2020-05-25 03:13

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_B00',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Rec', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('birthdate', models.DateField()),
                ('active_status', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Patient B00',
            },
        ),
        migrations.CreateModel(
            name='Patient_B01',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Insurance_Rec', models.CharField(max_length=100)),
                ('insurance_rec', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('middle_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('date_of_Birth', models.DateField()),
                ('relationship_to_Patient', models.CharField(max_length=100)),
                ('member_Id', models.IntegerField()),
                ('group_Id', models.IntegerField()),
                ('active_status', models.BooleanField(default=True)),
                ('patient_Rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud_register.Patient_B00')),
            ],
            options={
                'verbose_name': 'Patient_B01',
            },
        ),
        migrations.CreateModel(
            name='Patient_B02',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_Guardian_Rec', models.CharField(max_length=100)),
                ('first_Name', models.CharField(max_length=100)),
                ('middle_Name', models.CharField(max_length=100)),
                ('last_Name', models.CharField(max_length=100)),
                ('address_1', models.CharField(max_length=200)),
                ('address_2', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_Code', models.IntegerField()),
                ('phone_Home', phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31)),
                ('phone_Work', phone_field.models.PhoneField(blank=True, help_text='Phone Number', max_length=31)),
                ('eMail_Address', models.EmailField(max_length=100)),
                ('company_Rec', models.CharField(max_length=100)),
                ('active_status', models.BooleanField(default=True)),
                ('patient_Rec', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='crud_register.Patient_B00')),
                ('relationship_to_Patient', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.DO_NOTHING, to='crud_register.Patient_B01')),
            ],
            options={
                'verbose_name': 'Patient_B02',
            },
        ),
    ]
